#!/usr/bin/env bash
#displays the content of the file /etc/passwd .
#only displays the username, user id, and user home directory

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6;
done < "/etc/passwd"
