#!/usr/bin/env bash
#displays the content of the file /etc/passwd using the while loop + IFS

#!/bin/bash

while IFS=':' read -r username x user_id group_id user_info home_directory shell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory, and rides $shell."
    echo "USER ID's place is protected by the passcode $x, more info about the user here: $user_info"
    echo
done < "/etc/passwd"

