#!/usr/bin/env bash
# Displays "Best School" 10 times.
# On the 9th interaction, displays "Hi" before "Best School".

i=0

while [ $i -lt 10]
do
  if [$i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
