#!/usr/bin/env bash
#bash script that displays:

#the content of a working directory
#in a list format
#where only part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
